services:

  # app:
  #   build:
  #     context: ./app
  #     dockerfile: ./Dockerfile
  #   networks:
  #     - dev_net
  #   volumes:
  #    - .\app:/app

  valkey:
    container_name: valkey
    build:
      context: ./valkey
      dockerfile: ./Dockerfile
    networks:
      - dev_net
    ports:
      - "6379:6379"
    volumes:
      - .\valkey\data:/data/

  # valkey-vanilla:
  #   image: valkey/valkey:8.0.1-alpine
  #   restart: unless-stopped
  #   networks:
  #     - dev_net
  #   volumes:
  #     - .\valkey\data:/data

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    shm_size: 128mb
    networks:
      - dev_net
    ports:
      - "5432:5432"
    volumes:
      - .\postgres\data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test

  dbgate:
    container_name: dbgate
    image: dbgate/dbgate
    restart: unless-stopped
    networks:
      - dev_net
    ports:
      - "3000:3000"
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      BASIC_AUTH: true
      LOGINS: admin
      LOGIN_PASSWORD_admin: admin
      CONNECTIONS: postgres
      # CONNECTIONS: postgres, valkey
      LABEL_postgres: Postgres
      SERVER_postgres: postgres
      PORT_postgres: 5432
      USER_postgres: admin
      PASSWORD_postgres: admin
      ENGINE_postgres: postgres@dbgate-plugin-postgres
      # LABEL_valkey: valkey
      # SERVER_valkey: valkey
      # PORT_valkey: 6379
      # USER_valkey: admin
      # PASSWORD_valkey: admin
      # URL_valkey: valkey://admin:admin@localhost:6379/0
      # ENGINE_valkey: redis@dbgate-plugin-redis


networks:
  dev_net:
    driver: bridge

volumes:
  dbgate-data:
    external: true