services:

  # alpine:
  #   container_name: alpine
  #   build:
  #     context: ./alpine
  #     dockerfile: ./Dockerfile
  #   networks:
  #     - dev_net
  #   volumes:
  #    - .\alpine\src:/home/devel

  valkey:
    container_name: valkey
    build:
      context: ./valkey
      dockerfile: ./Dockerfile
    networks:
      - dev_net
    ports:
      - "6379:6379"
    volumes:
      - .\valkey\data:/data/

  # valkey-vanilla:
  #   image: valkey/valkey:8.0.1-alpine
  #   restart: unless-stopped
  #   networks:
  #     - dev_net
  #   volumes:
  #     - .\valkey\data:/data

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    networks:
      - dev_net
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - .\mariadb\data:/var/lib/mysql

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    shm_size: 128mb
    networks:
      - dev_net
    ports:
      - "5432:5432"
    volumes:
      - .\postgres\data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test

  dbgate:
    container_name: dbgate
    image: dbgate/dbgate:alpine
    restart: unless-stopped
    networks:
      - dev_net
    ports:
      - "3000:3000"
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      BASIC_AUTH: true
      LOGINS: admin
      LOGIN_PASSWORD_admin: admin
      CONNECTIONS: mysql, mongo # postgres
      LABEL_mysql: MariaDB
      SERVER_mysql: localhost
      USER_mysql: root
      PASSWORD_mysql: example
      PORT_mysql: 3306
      ENGINE_mysql: mysql@dbgate-plugin-mysql

#      LABEL_con1: MongoDB
#      URL_mongo: mongodb://root:example@mongo:27017/
#      ENGINE_mongo: mongo@dbgate-plugin-mongo

#      LABEL_postgres: Postgres
#      SERVER_postgres: postgres
#      PORT_postgres: 5432
#      USER_postgres: admin
#      PASSWORD_postgres: admin
#      ENGINE_postgres: postgres@dbgate-plugin-postgres

networks:
  dev_net:
    driver: bridge

volumes:
  dbgate-data:
    external: true